//
//  GlobalShortcutConfigurationPolicy.swift
//  LocalKeyRemapper
//
//  Created by Alessandro Giuriati on 7/18/26.
//

import CoreGraphics

/// Represents an invalid application shortcut configuration.
nonisolated enum GlobalShortcutConfigurationError:
    Error,
    Equatable
{
    /// Two application commands use the same key combination.
    case duplicateShortcut

    /// A global shortcut does not contain any modifier and
    /// would interfere with normal typing.
    case insufficientModifiers(
        GlobalShortcutAction
    )
}

/// Describes one blocking conflict between an active remapping rule
/// and an application-wide remapping shortcut.
///
/// A conflict is blocking only when the shortcut is claimed by an exact
/// mapping:
///
/// - an Exact Only rule whose complete source equals the shortcut;
/// - an enabled exact exception inside a Preserve Modifiers rule;
/// - either equivalent case generated by Reverse.
///
/// A Preserve Modifiers parent rule that merely uses the same physical key
/// is not a blocking conflict. It is represented separately as a warning.
nonisolated struct RemappingShortcutRuleConflict:
    Error,
    Equatable
{
    /// Position of the conflicting rule in the validated rule collection.
    let ruleIndex: Int

    /// Application command assigned to the conflicting shortcut.
    let action: GlobalShortcutAction

    /// Exact shortcut combination claimed by the rule or one of its
    /// enabled exceptions.
    let shortcut: KeyCombination

    /// User-facing name of the conflicting application shortcut.
    var shortcutTitle: String {
        switch action {
        case .toggle:
            return "Toggle Remapping"

        case .enable:
            return "Enable Remapping"

        case .disable:
            return "Disable Remapping"
        }
    }

    /// Clear blocking message shared by every validation entry point.
    var message: String {
        "This rule contains an exact mapping that conflicts with the \(shortcutTitle) shortcut. Change the rule, remove the matching exception, or choose a different shortcut before saving."
    }
}

/// Describes one non-blocking interaction between a Preserve Modifiers rule
/// and an application-wide remapping shortcut.
///
/// The shortcut remains reserved for the application and will not be
/// remapped by the parent Preserve Modifiers rule. Every other modifier
/// combination using the same physical key remains available to the rule.
nonisolated struct RemappingShortcutRuleWarning:
    Equatable
{
    /// Position of the affected rule in the evaluated rule collection.
    let ruleIndex: Int

    /// Application command assigned to the reserved shortcut.
    let action: GlobalShortcutAction

    /// Exact shortcut combination reserved for the application.
    let shortcut: KeyCombination

    /// User-facing name of the reserved application shortcut.
    var shortcutTitle: String {
        switch action {
        case .toggle:
            return "Toggle Remapping"

        case .enable:
            return "Enable Remapping"

        case .disable:
            return "Disable Remapping"
        }
    }

    /// Describes what the reserved shortcut does instead of being remapped.
    var reservedBehaviorDescription: String {
        switch action {
        case .toggle:
            return "toggle remapping"

        case .enable:
            return "enable remapping"

        case .disable:
            return "disable remapping"
        }
    }
}

/// Detects blocking conflicts and non-blocking warnings between remapping
/// rules and application shortcuts.
///
/// Classification follows the runtime precedence used by the application:
///
/// - disabled rules do not participate;
/// - Exact Only rules claim only their complete source combination;
/// - Preserve Modifiers parent rules claim a physical key but application
///   shortcuts remain reserved before remapping is applied;
/// - therefore a parent Preserve Modifiers match produces a warning;
/// - an enabled exact exception matching the shortcut is rejected because it
///   explicitly configures a combination reserved for the application;
/// - both Pass Through and Replace With exceptions are rejected;
/// - Reverse contributes its generated source direction and mirrored
///   exceptions.
///
/// Toggle, Enable, and Disable use the same deterministic policy.
nonisolated enum RemappingShortcutRuleConflictPolicy {

    private enum DirectionInteraction:
        Equatable
    {
        case none
        case preserveWarning
        case blockingConflict
    }

    /// Rejects the first blocking conflict.
    ///
    /// Non-blocking Preserve Modifiers warnings never cause this method
    /// to throw.
    static func validate(
        rules: [RemapRule],
        shortcutConfiguration:
            RemappingShortcutConfiguration
    ) throws {
        guard
            let conflict =
                conflicts(
                    rules:
                        rules,
                    shortcutConfiguration:
                        shortcutConfiguration
                )
                .first
        else {
            return
        }

        throw conflict
    }

    /// Returns every blocking conflict in deterministic
    /// shortcut-and-rule order.
    static func conflicts(
        rules: [RemapRule],
        shortcutConfiguration:
            RemappingShortcutConfiguration
    ) -> [RemappingShortcutRuleConflict] {
        var detectedConflicts:
            [RemappingShortcutRuleConflict] = []

        for registration in
            shortcutConfiguration.registrations
        {
            for (
                ruleIndex,
                rule
            ) in rules.enumerated()
            where hasBlockingConflict(
                registration.shortcut,
                rule:
                    rule
            ) {
                detectedConflicts.append(
                    RemappingShortcutRuleConflict(
                        ruleIndex:
                            ruleIndex,
                        action:
                            registration.action,
                        shortcut:
                            registration.shortcut
                    )
                )
            }
        }

        return detectedConflicts
    }

    /// Returns every non-blocking Preserve Modifiers warning in
    /// deterministic shortcut-and-rule order.
    static func warnings(
        rules: [RemapRule],
        shortcutConfiguration:
            RemappingShortcutConfiguration
    ) -> [RemappingShortcutRuleWarning] {
        var detectedWarnings:
            [RemappingShortcutRuleWarning] = []

        for registration in
            shortcutConfiguration.registrations
        {
            for (
                ruleIndex,
                rule
            ) in rules.enumerated()
            where producesPreserveWarning(
                registration.shortcut,
                rule:
                    rule
            ) {
                detectedWarnings.append(
                    RemappingShortcutRuleWarning(
                        ruleIndex:
                            ruleIndex,
                        action:
                            registration.action,
                        shortcut:
                            registration.shortcut
                    )
                )
            }
        }

        return detectedWarnings
    }

    /// Returns whether one active rule contains an exact mapping that claims
    /// the supplied application shortcut.
    static func hasBlockingConflict(
        _ shortcut: KeyCombination,
        rule: RemapRule
    ) -> Bool {
        interaction(
            for:
                shortcut,
            rule:
                rule
        ) == .blockingConflict
    }

    /// Compatibility entry point retained for existing UI code.
    ///
    /// It now reports only blocking exact conflicts. A parent Preserve
    /// Modifiers match is intentionally excluded and can be queried through
    /// `producesPreserveWarning(_:rule:)`.
    static func effectivelyMatches(
        _ shortcut: KeyCombination,
        rule: RemapRule
    ) -> Bool {
        hasBlockingConflict(
            shortcut,
            rule:
                rule
        )
    }

    /// Returns whether one active Preserve Modifiers direction uses the same
    /// physical key as the shortcut without defining an enabled exact
    /// exception for that precise combination.
    static func producesPreserveWarning(
        _ shortcut: KeyCombination,
        rule: RemapRule
    ) -> Bool {
        interaction(
            for:
                shortcut,
            rule:
                rule
        ) == .preserveWarning
    }

    /// Combines the forward and optional generated reverse directions.
    ///
    /// A blocking conflict takes precedence over a warning when both
    /// directions interact with the same shortcut.
    private static func interaction(
        for shortcut: KeyCombination,
        rule: RemapRule
    ) -> DirectionInteraction {
        guard rule.isEnabled else {
            return .none
        }

        let forwardInteraction =
            directionInteraction(
                shortcut,
                source:
                    rule.source,
                matchingMode:
                    rule.matchingMode,
                overrides:
                    rule.overrides
            )

        if forwardInteraction
            == .blockingConflict
        {
            return .blockingConflict
        }

        guard rule.isBidirectional else {
            return forwardInteraction
        }

        let reverseInteraction =
            directionInteraction(
                shortcut,
                source:
                    rule.destination,
                matchingMode:
                    rule.matchingMode,
                overrides:
                    reverseOverrides(
                        from:
                            rule.overrides,
                        reverseSourceKeyCode:
                            rule.destination.keyCode
                    )
            )

        if reverseInteraction
            == .blockingConflict
        {
            return .blockingConflict
        }

        if forwardInteraction
            == .preserveWarning
            || reverseInteraction
                == .preserveWarning
        {
            return .preserveWarning
        }

        return .none
    }

    /// Classifies one forward or generated reverse direction.
    private static func directionInteraction(
        _ shortcut: KeyCombination,
        source: KeyCombination,
        matchingMode: RemapMatchingMode,
        overrides: [RemapOverride]
    ) -> DirectionInteraction {
        switch matchingMode {
        case .exact:
            return source == shortcut
                ? .blockingConflict
                : .none

        case .preserveModifiers:
            guard
                source.keyCode
                    == shortcut.keyCode
            else {
                return .none
            }

            let hasEnabledExactException =
                overrides.contains {
                    remapOverride in

                    remapOverride.isEnabled
                        && remapOverride.source
                            == shortcut
                }

            if hasEnabledExactException {
                // Any enabled exact exception is an explicit configuration
                // for a combination reserved by the application shortcut.
                //
                // Pass Through would be redundant and Replace With would
                // never be allowed to take precedence over the shortcut.
                return .blockingConflict
            }

            // The parent Preserve Modifiers rule can remain active. The
            // application shortcut is reserved separately at runtime and
            // therefore bypasses this single modifier combination.
            return .preserveWarning
        }
    }

    /// Mirrors stored exceptions exactly as the remapping engine does
    /// for the generated Reverse direction.
    private static func reverseOverrides(
        from overrides: [RemapOverride],
        reverseSourceKeyCode:
            CGKeyCode
    ) -> [RemapOverride] {
        overrides.map {
            remapOverride in

            RemapOverride(
                source:
                    KeyCombination(
                        keyCode:
                            reverseSourceKeyCode,
                        modifiers:
                            remapOverride
                                .source
                                .modifiers
                    ),
                action:
                    remapOverride.action,
                isEnabled:
                    remapOverride.isEnabled
            )
        }
    }
}

/// Represents non-blocking guidance for a valid shortcut configuration.
nonisolated enum GlobalShortcutConfigurationSuggestion:
    Equatable
{
    /// At least one shortcut combines Fn with F1 through F12.
    case fnWithFunctionKey

    /// At least one shortcut uses exactly one modifier.
    case useAdditionalModifier

    var message:
        String
    {
        switch self {
        case .fnWithFunctionKey:
            return KeyCombinationConfigurationWarning
                .fnWithFunctionKey
                .message

        case .useAdditionalModifier:
            return "Using only one modifier may conflict with shortcuts in other applications. Two or more modifiers are recommended."
        }
    }
}

/// Applies deterministic validation and guidance rules to global shortcuts.
///
/// This policy does not inspect keyboard input and does not assume that
/// macOS uses its default shortcuts. Real availability is verified later
/// by attempting registration with the operating system.
nonisolated enum GlobalShortcutConfigurationPolicy {

    /// Rejects only configurations that are internally unsafe or ambiguous.
    static func validate(
        _ configuration:
            RemappingShortcutConfiguration
    ) throws {
        var seenShortcuts:
            Set<KeyCombination> = []

        for registration in
            configuration.registrations
        {
            guard
                registration
                    .shortcut
                    .modifiers
                    .rawValue
                    .nonzeroBitCount
                    >= 1
            else {
                throw GlobalShortcutConfigurationError
                    .insufficientModifiers(
                        registration.action
                    )
            }

            guard
                seenShortcuts
                    .insert(
                        registration.shortcut
                    )
                    .inserted
            else {
                throw GlobalShortcutConfigurationError
                    .duplicateShortcut
            }
        }
    }

    /// Returns non-blocking guidance for a valid configuration.
    ///
    /// A specific Fn and function-key warning takes precedence over the
    /// more general recommendation to use two or more modifiers.
    static func suggestion(
        for configuration:
            RemappingShortcutConfiguration
    ) -> GlobalShortcutConfigurationSuggestion? {
        let usesFnWithFunctionKey =
            configuration
                .registrations
                .contains {
                    registration in

                    KeyCombinationConfigurationWarningPolicy
                        .warning(
                            for:
                                registration.shortcut
                        )
                        == .fnWithFunctionKey
                }

        if usesFnWithFunctionKey {
            return .fnWithFunctionKey
        }

        let usesOneModifier =
            configuration
                .registrations
                .contains {
                    registration in

                    registration
                        .shortcut
                        .modifiers
                        .rawValue
                        .nonzeroBitCount
                        == 1
                }

        return usesOneModifier
            ? .useAdditionalModifier
            : nil
    }
}
